### ISSUE TITLE
SSplot_Ensemble

### ISSUE THREAD

**Issue by jabbamodel** [nmfs-ost/ss3diags#28]
There are some major changes that are not ideally designed with several issues:
(1) Wrong description and keywords as:
#' Hindcasting Cross-Validations 
#'
#' Plots one-step ahead hindcasting cross-validations and computes MASE from prediction residuals
(2)  the argument summaryoutput may conflict with other functions of the plot and the @param is not in the correct position

#' @keywords ssplot hindcasting

I have not tested this fully, but one option is to outsource the options of comparing model fits into a separate function to facilitate easy use? At a minimum I suggest to use summaryoutput="missing" or summaryoutput = NULL to retain functioning without having to input summaryoutput

**Comment by jabbamodel** [comment]
Suggest header:
#' SSplotEnsemble() 
#'
#' Plots model ensembles and forecasts with uncertaity represented by MVLN or MCMC posteriors

Again this plot was designed to compare generated distributions of key quantities from MCMC and MVLN objects. Indices don't have these properties in SS3 with expected values typically excluded from the covar and mcmc

Also, r4ss::SSplotComparisons() has already this option.  In ss3diags, the more suitable plot for this option is SSplotModelcomp(), where the cpue comparison is already available.  I would therefore recommend to drop the summaryoutput requirement and ensemble_plot_index() from SSplotEnsemble()

**Comment by MOshima-PIFSC** [comment]
@jabbamodel Thanks for catching these issues. I made the change to the SSplotEnsemble header and @keywords, with a slight modification to the first line. Instead of just having the function name I put:
#' Model ensemble plots

Additionally the summaryoutput and ensemble_plot_index portion was removed from the function. 
Fixes are pushed to the [SSplotEnsemble-issue](https://github.com/PIFSCstockassessments/ss3diags/tree/SSplotEnsemble-issue) branch commit [6cc7e40](https://github.com/PIFSCstockassessments/ss3diags/commit/6cc7e403009569dfb2adad9078287c9626f6694c)

**Comment by MOshima-PIFSC** [comment]
@jabbamodel Feel free to check these changes and if you think they are good, I can close the issue. Thanks!
