### ISSUE TITLE
SSplotJABBAres() 

### ISSUE THREAD

**Issue by N-DucharmeBarth-NOAA** [nmfs-ost/ss3diags#50]
It could be useful to be able to run this function with the option to only output the RMSEtable and turn off all plotting. Alternatively, the RMSE calculations could be relocated to a standalone function that could be called independently of the plotting function.

**Comment by MOshima-PIFSC** [comment]
@N-DucharmeBarth-NOAA this is a good suggestion. I think it might be good to move the RMSE to a separate function that way it can be used on its own. Thanks!

**Comment by N-DucharmeBarth-NOAA** [comment]
Great! It may also be worth checking to see that all functions that produce a table of diagnostics (runs test, retrospective, hindcasting, etc.) can have the plotting turned off if desired.

**Comment by MOshima-PIFSC** [comment]
This is something I looked into earlier and if I'm remembering correctly, most of the functions would need to be re-written to save the output table separately, at the time it seemed like it would be a fair amount of work. However, it might be worth taking the time to do this now for CAPAM the project because it would improve the overall usability I think.
