### ISSUE TITLE
Smaller Example Data filesize

### ISSUE THREAD

**Issue by efletcherPIFSC** [nmfs-ost/ss3diags#68]
```
❯ checking installed package size ... NOTE
    installed size is 12.4Mb
    sub-directories of 1Mb or more:
      data  11.9Mb
```
CRAN maximum (installed) package file size limit is 5MB  

`*.rda` Datafile fileslzes
```
mcmcsimple.rda 152.8 KB
simple.rda 1.1 MB
retroSimple.rda 5.7 MB
```

**Comment by MOshima-PIFSC** [comment]
I don't think we will be able to reduce the data down to a size small enough for CRAN, even if we just submit it separately as a data package. I found this [option](https://thecoatlessprofessor.com/programming/r/r-data-packages-in-external-data-repositories-using-the-additional_repositories-field/) that allows you to create a GitHub repo for a data package and allows users to install that package regularly using `install.packages("datapackage")` and then load the data via `data("dataset", package="datapackage")`. 
@efletcherPIFSC I'm wondering if it would be helpful to collaborate with the SS/r4ss team on developing this package, that way these example SS runs could be used by their package too? And it could be hosted by either the nmfs-stock-synthesis or r4ss organizations.

**Comment by MOshima-PIFSC** [comment]
We have decided to separate the data from the ss3diags package to keep functionality and allow us to publish on CRAN. 
Next steps: 

- [ ] For testing purposes, replace rda files with the simple stock synthesis input model [files](https://github.com/nmfs-stock-synthesis/user-examples/tree/main/model_files/simple) into data folder and write code to run the model and retrospectives to create the output for unit tests.
- [ ] Remove rda files in data folder
- [ ] Ask Kathryn about options for hosting the he simple stock synthesis input model files and ss executable to allow people to run the model themselves (for reproducibility)

**Comment by MOshima-PIFSC** [comment]
I created the FEAT-update-testing-fixture branch to work on this. Based on communication with the r4ss team, we are going to remove the simple SS model in our data folder and use the [simple_small](https://github.com/r4ss/r4ss/tree/main/inst/extdata/simple_small) SS model. Since r4ss is a dependency of ss3diags we can call the simple_small Report.sso using `system.file("extdata", "simple_small", package= "r4ss")`. 
To run the retrospective and hindcast tests (`SSmase_test.R`, `test-HCxval.R`, and `test-retro.R`), we can add something like [this ](https://github.com/r4ss/r4ss/blob/e766b470d7bfc4b58d1152ccc25ef6d35b85538a/tests/testthat/test-runs.R#LL43C2-L51C4)to the test fixtures to run the retrospectives. The SS executable can be retrieved via a github action.

**Comment by MOshima-PIFSC** [comment]
Currently tests are running and passing on unbuntu set up. Next step is to add in windows and mac OS to config matrix. 
@efletcherPIFSC I created an [inst/extdata](https://github.com/PIFSCstockassessments/ss3diags/tree/FEAT-update-testing-fixtures/inst/extdata) directory and put the input files in there and am copying the ss exe to there. Then in the tests I am copying all those files to a temp dir and running retrospectives there. If we do this, we should be able to delete the simple.rda, retroSimple.rda, and mcmcSimple.rda objects later on. Before we remove them from the package we will need to update the documentation so that these objects are created at time of knitting the docs. What do you think about this?

**Comment by MOshima-PIFSC** [comment]
Tests are running and passing on all OS configurations now (ubuntu, windows, and macOS). The next step would be to update the documentation and vignettes to use these model structures. Adding this issue to milestone "Documentation".
